# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 'coffeehours.net'
author: 'Coffee Hours'
copyright: "2022"
logo: logo.svg

# Information about where the book exists on the web
repository:
  url: https://github.com/coffee-hours/coffeehours.github.io  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
        <div><script src="https://giscus.app/client.js"
        data-repo="coffee-hours/coffeehours.github.io"
        data-repo-id="R_kgDOGr3NeQ"
        data-category="General"
        data-category-id="DIC_kwDOGr3Nec4CAuVZ"
        data-mapping="title"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-theme="light"
        data-lang="en"
        crossorigin="anonymous"
        async></script></div>
